const dotEnvResult = require('dotenv').config()
if (dotEnvResult.error) {
  throw dotEnvResult.error
}

const validate_IBC = require("./validate_IBC");
const apply_IBC = require("./apply_IBC");
const axios = require("axios");

let IBC;

async function validateIBC() {
  var result =
  {
    isValid: true,
    errors: []
  };

  // Load dependencies from github and validate modules.
  for (var moduleConfig of IBC.modules) {
    const validateResult = await validate_IBC.validateModule(IBC, moduleConfig);
    if (!validateResult.isValid) {
      result.isValid = false;
      result.errors = result.errors.concat(validateResult.errors);
    }
  }

  if (!result.isValid) {
    throw result;
  }

  return result;
}

async function applyIBC() {
  switch (IBC.platform) {
    case "android":
      applyAndroidIBC();
      break;
    case "ios":
      applyiOSIBC();
      break;
  }
}

function applyAndroidIBC() {

}

async function applyiOSIBC() {
  const applyPlistResult = apply_IBC.applyIBCToPlist(IBC);
  if (!applyPlistResult.success) {
    throw applyPlistResult;
  }

  const applyPodfileResult = await apply_IBC.applyIBCToPodfile(IBC);
  if (!applyPodfileResult.success) {
    throw applyPodfileResult;
  }
}

async function main() {
  const fs = require('fs');

  if (!('BITRISE_SOURCE_DIR' in process.env)) {
    throw new Error('The [BITRISE_SOURCE_DIR] environment variable is missing. If you are running locally (not bitrise) please define it in the .env file.');
  }

  var IBCPath = "";
  // Write the IBC to the root of the bitrise source dir.
  if ('IBC' in process.env) {
    // When working with CI, write the IBC to the workspace so it's versionned.
    IBCPath = process.env.BITRISE_SOURCE_DIR + "/ivory_build_config.json";
    console.log(`Writing [${IBCPath}] from 'IBC' Environment Variable.`);
    fs.writeFileSync(IBCPath, process.env.IBC);
  } else if ('IBC_PATH' in process.env) {
    // IBC is local with a path.
    IBCPath = process.env.IBC_PATH + 'ivory_build_config.json';
    var rawBuildConfig = fs.readFileSync(IBCPath);
    IBC = JSON.parse(rawBuildConfig);
  } else {
    throw new Error('Invalid workflow parameters, you must either have an "IBC" or "IBC_PATH" environment variable in your environment to run.');
  }

  // Read the IBC from the root of the source dir.
  // NOTE: This is important so the build process does not depend on environment variables but rather
  // files on IO so it can be loaded from github PRs and other sources.
  // An example of this is once the IBC is applied/validated, the github PR generated by Scrimshaw
  // will no longer depend on the process.env IBC but rather the locally stored ivory_build_config.json file.
  var rawBuildConfig = fs.readFileSync(IBCPath);
  IBC = JSON.parse(rawBuildConfig);
  IBC.workspace = process.env.BITRISE_SOURCE_DIR + "/";

  await validateIBC();
  await applyIBC();
}

(async () => {
  try {
    await main();
  }
  catch (e) {
    console.log(e);

    if (e.hasOwnProperty('errors')) {
      console.log("Errors:")
      for (var i = 0; i < e.errors.length; i++) {
        console.log(e.errors[i]);
      }
    }

    // Throw to bitrise
    throw e;
  }

  return 0;
})();
